Множественые изменения
1C-Connect/1cconnect-text-bot pull request #11
Opened 2024-10-14 09:47 UTC by LilKirill00

- добавлена возможность редактировать различные сообщения об ошибках пользователю через error_messages (см. Readme)
- исправлены неправильно передающиеся параметры в exec_button
- реализован параметр offer_options для save_to_var позволяющий пользователю предложить свой вариант для ответа
- исправлены мелкие ошибки
- рефактор некоторых повторяющихся моментов кода
- ! перемещение файлов в правильную дерикторию !

2024-10-16 09:10 UTC, polyn0m requested changes

2024-10-16 09:10 UTC, polyn0m commented on bot/bot.go
> +	// строим абсолютный путь к переданной директории
Такие комментарии излишние, загрязняют код не неся никакого смысла. Из кода и так понятно что строится абсолютный путь.  Лучше комментировать бизнес логику не ясную из кода

2024-10-16 09:10 UTC, polyn0m commented on bot/bot.go
> +	// обходим все файлы и папки
тоже самое

2024-10-16 09:10 UTC, polyn0m commented on bot/bot.go
> +// проверить является ли файл изображением
тоже самое, можно дать название функции более понятное ну и далее в файла тоже есть, если комент очевиден с кодом, то он не нужен, код сам о себе все говорит

2024-10-22 09:40 UTC, polyn0m approved these changes

2024-10-22 10:35 UTC, ros-tel approved these changes

2024-10-30 05:36 UTC, merged