feat: Реализована возможность перевода на случайного спеца из списка
1C-Connect/1cconnect-text-bot pull request #4
Opened 2024-08-13 04:38 UTC by LilKirill00

2024-08-13 07:18 UTC, ros-tel commented on bot/bot.go
> +					} else {
else лишний, т.к. при выполнении условия `return`

2024-08-13 07:18 UTC, ros-tel commented on bot/messages/text.go
> +func (msg *Message) GetSpecialistsAvailable(c *gin.Context) (available []uuid.UUID, err error) {
думаю, стоит заменить `available` на `spec_ids`
в таком случае отпадет необходимость в объявлении ниже переменной `var spec_ids []uuid.UUID` и достаточно делать просто `return` вместо `return []uuid.UUID{}, err`

2024-08-13 08:38 UTC, ros-tel approved these changes

2024-08-13 08:54 UTC, polyn0m requested changes

2024-08-13 08:54 UTC, polyn0m commented on botconfig_parser/menu.go
> +	AppointSpecFromListButton *[]uuid.UUID `yaml:"appoint_spec_from_list_button,omitempty"`
Название плохо отражает суть действия, тогда уж надо назвать **AppointRandomSpecFromListButton**

2024-08-13 11:48 UTC, LilKirill00 commented on botconfig_parser/menu.go
> +	AppointSpecFromListButton *[]uuid.UUID `yaml:"appoint_spec_from_list_button,omitempty"`
исправлено

2024-08-23 07:23 UTC, polyn0m approved these changes

2024-08-23 07:24 UTC, merged