feat: Реализована работа с кастомными перемеными
1C-Connect/1cconnect-text-bot pull request #5
Opened 2024-08-31 10:55 UTC by LilKirill00

можно запросить текст у пользователя через save_said можно использовать полученые данные в exec_button

2024-09-02 04:14 UTC, ros-tel approved these changes

2024-09-02 08:42 UTC, polyn0m requested changes

2024-09-02 08:42 UTC, polyn0m commented on README.md
> +          save_said:
Я бы лучше этот блок назвал **save_to_var**, а внутри **save_to_var** -> **var_name**

2024-09-05 07:51 UTC, polyn0m approved these changes

2024-09-09 06:22 UTC, closed without merging